### ISSUE TITLE
Math Magicians: Project Day4

### ISSUE THREAD

**Issue by AbdimulhinYussuf3675** [AbdimulhinYussuf3675/Math_Magicians#4]
I imported `useState` from react to handle the data from the calculator. The function returns an array that takes in `state` and `setState` that when referenced in the UI and the value changes when the User clicks a specific button react will update the state change.

**Comment by DammyShittu** [comment]
Hi @AbdimulhinYussuf3675,

## APPROVED 🟢

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
